[package]
name = "basic-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
arduino-hal = { git = "https://github.com/Rahix/avr-hal", features = ["arduino-uno"] }

[profile.dev]
opt-level="s"
panic = "abort"

[profile.release]
opt-level="s"
panic = "abort"
